// <auto-generated />
using System;
using Livetta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Livetta.Infrastructure.Migrations
{
    [DbContext(typeof(LivettaDbContext))]
    [Migration("20250904200058_0.0.1")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Livetta.Infrastructure.Persistence.Entities.ContactsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("ResidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_contacts_resident_id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Livetta.Infrastructure.Persistence.Entities.ResidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_residents");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("Livetta.Infrastructure.Persistence.Entities.ContactsEntity", b =>
                {
                    b.HasOne("Livetta.Infrastructure.Persistence.Entities.ResidentEntity", "Resident")
                        .WithOne("Contacts")
                        .HasForeignKey("Livetta.Infrastructure.Persistence.Entities.ContactsEntity", "ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contacts_residents_resident_id");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Livetta.Infrastructure.Persistence.Entities.ResidentEntity", b =>
                {
                    b.Navigation("Contacts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
